# Generated by Django 5.0.6 on 2024-07-20 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrol_cng_stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cng_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('petrol_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('diesel_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petrol_cng_stations.city')),
            ],
        ),
        migrations.DeleteModel(
            name='CNGPrice',
        ),
    ]
