# Generated by Django 5.0.6 on 2024-07-20 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrol_cng_stations', '0003_cngprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='DieselPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petrol_cng_stations.city')),
            ],
            options={
                'get_latest_by': 'date',
            },
        ),
    ]
