# Generated by Django 5.0.6 on 2024-07-24 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrol_cng_stations', '0006_fuelmodel_state_city_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='LPGPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('previous_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petrol_cng_stations.city')),
            ],
        ),
        migrations.CreateModel(
            name='PetrolPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('previous_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petrol_cng_stations.city')),
            ],
        ),
    ]
