# Generated by Django 5.0.6 on 2024-07-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carshanders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Expo',
        ),
    ]
