# Generated by Django 5.0.6 on 2024-07-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshanders', '0002_delete_event_delete_expo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('interior', 'Interior'), ('exterior', 'Exterior'), ('other', 'Other')], max_length=20)),
            ],
        ),
    ]
