# Generated by Django 5.0.6 on 2024-07-30 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshanders', '0004_caraccessory_shop_tyremanufacturer_tyretype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecenter',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='servicecenter',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicecenter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicecenter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='servicecenter',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterUniqueTogether(
            name='servicecenter',
            unique_together={('name', 'city')},
        ),
    ]
