# Generated by Django 5.0.6 on 2024-07-30 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshanders', '0005_alter_servicecenter_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbrand',
            name='description',
        ),
        migrations.RemoveField(
            model_name='carbrand',
            name='logos',
        ),
        migrations.AlterField(
            model_name='servicecenter',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_centers', to='carshanders.carbrand'),
        ),
    ]
