# Generated by Django 5.0.6 on 2024-07-30 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshanders', '0006_remove_carbrand_description_remove_carbrand_logos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecenter',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
