# Generated by Django 5.0.6 on 2024-07-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshanders', '0007_alter_servicecenter_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
