# Generated by Django 5.0.6 on 2024-07-30 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carshanders', '0009_alter_carbrand_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicecenter',
            unique_together=set(),
        ),
    ]
