# Generated by Django 5.0.6 on 2024-08-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshanders', '0011_categorycomponent_remove_component_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrand',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicecenter',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecenter',
            name='working_hours',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
