# Generated by Django 5.0.6 on 2024-08-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshanders', '0012_carbrand_is_active_servicecenter_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profitdata',
            name='profit',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
