# Generated by Django 5.0.6 on 2024-07-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('length', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('width', models.CharField(max_length=100)),
                ('wheelbase', models.CharField(max_length=100)),
                ('kerb', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('ground', models.CharField(max_length=100)),
                ('trunk', models.CharField(max_length=100)),
                ('tank', models.CharField(max_length=100)),
                ('engine', models.CharField(max_length=100)),
                ('gears', models.CharField(max_length=100)),
                ('fueleconomy', models.CharField(max_length=100)),
                ('speed', models.CharField(max_length=100)),
                ('bags', models.CharField(max_length=100)),
                ('belt', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('manufac_place', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PetrolPump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=200)),
                ('Address', models.TextField()),
                ('CompanyName', models.CharField(max_length=100)),
            ],
        ),
    ]
