# Generated by Django 5.0.6 on 2024-07-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petrolpump',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='petrolpump',
            name='City',
        ),
        migrations.RemoveField(
            model_name='petrolpump',
            name='CompanyName',
        ),
        migrations.RemoveField(
            model_name='petrolpump',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='petrolpump',
            name='State',
        ),
        migrations.AddField(
            model_name='petrolpump',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='petrolpump',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='petrolpump',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='petrolpump',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='petrolpump',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='petrolpump',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
