# Generated by Django 5.0.6 on 2024-07-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_petrolpump_address_remove_petrolpump_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, default='No description available.', null=True),
        ),
    ]
