# Generated by Django 5.0.6 on 2024-07-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='description',
        ),
        migrations.AddField(
            model_name='car',
            name='Vehicle_overview',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.TextField(null=True),
        ),
    ]
