# Generated by Django 5.0.6 on 2024-07-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.CharField(default='defult_image_path.jpg', max_length=1000),
            preserve_default=False,
        ),
    ]
