# Generated by Django 5.0.6 on 2025-02-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_car_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='bags',
            new_name='airbags',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='belt',
            new_name='fuel_economy',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='fueleconomy',
            new_name='fuel_tank_capacity',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='ground',
            new_name='ground_clearance',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='speed',
            new_name='seat_belts',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='tank',
            new_name='top_speed',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='trunk',
            new_name='trunk_capacity',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='Vehicle_overview',
            new_name='vehicle_overview',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='type',
            new_name='vehicle_type',
        ),
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Pickup', 'Pickup Truck')], default='Sedan', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('EV', 'Electric Vehicle'), ('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG', 'Compressed Natural Gas'), ('Hybrid', 'Hybrid')], default='Petrol', max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='manufacturer',
            field=models.CharField(choices=[('GM', 'General Motors'), ('HM', 'Hindustan Motors'), ('LR', 'Land Rover'), ('RR', 'Rolls Royce'), ('DC', 'DaimlerChrysler')], default='GM', max_length=2),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.CharField(blank=True, help_text='Mileage (e.g., km/l or miles/gal)', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='num_of_cylinders',
            field=models.PositiveIntegerField(default=4, help_text='Number of engine cylinders'),
        ),
        migrations.AddField(
            model_name='car',
            name='user_rating',
            field=models.FloatField(default=0.0, help_text='Rating out of 5'),
        ),
    ]
