# Generated by Django 5.0.6 on 2026-01-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_rename_bags_car_airbags_rename_belt_car_fuel_economy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.CharField(choices=[('GM', 'General Motors'), ('HM', 'Hindustan Motors'), ('LR', 'Land Rover'), ('RR', 'Rolls Royce'), ('DC', 'DaimlerChrysler'), ('VW', 'Volkswagen Group'), ('BMW', 'BMW Group'), ('MB', 'Mercedes-Benz'), ('TO', 'Toyota'), ('HO', 'Honda'), ('HY', 'Hyundai'), ('MA', 'Maruti Suzuki'), ('TA', 'Tata Motors'), ('NI', 'Nissan'), ('SK', 'Skoda')], default='GM', max_length=3),
        ),
    ]
