# Generated by Django 5.0.6 on 2026-01-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_car_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
