# Generated by Django 5.0.6 on 2026-01-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_car_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
