# Generated by Django 5.0.6 on 2024-07-29 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New_Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('engine', models.CharField(max_length=100)),
                ('horsepower', models.IntegerField()),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(upload_to='cars/')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(default='default_brand', max_length=255)),
                ('engine', models.CharField(max_length=100)),
                ('power_torque', models.CharField(max_length=100)),
                ('kerb_weight', models.CharField(blank=True, max_length=100, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=200, null=True)),
                ('estimated_price', models.CharField(max_length=100)),
                ('expected_launch', models.CharField(max_length=100)),
                ('description', models.TextField(default='default_description')),
                ('image', models.ImageField(upload_to='cars/')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='New_Car_Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=200)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='newCar.new_car')),
            ],
        ),
    ]
