# Generated by Django 5.0.6 on 2024-07-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newCar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_car_feature',
            name='feature',
            field=models.TextField(),
        ),
    ]
