# Generated by Django 5.0.6 on 2024-07-31 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newCar', '0002_alter_new_car_feature_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomingcar',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='upcomingcar',
            name='kerb_weight',
        ),
    ]
