# Generated by Django 5.0.6 on 2024-07-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newCar', '0003_remove_upcomingcar_dimensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingcar',
            name='dimensions',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='upcomingcar',
            name='kerb_weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
