function header()
{
	document.write("<!-- Header start --><div id='header'><div class='logo'><a href='http://www.mapsofindia.com/india/india.html' title='Maps Of India'><img src='http://www.business.mapsofindia.com/images-new/moi-logo.png' width='90' height='88' border='0' alt='Maps Of India' /></a></div><div class='header_frame'><div class='header-text1'>Nobody Covers <u><a href='http://www.mapsofindia.com/maps/india/india-political-map.htm' class='header-text1'>India</a></u> as we do</div><div class='header-text2'><a href='http://www.mapsofindia.com/maps/india/india-political-map.htm' class='header-text2'>Maps</a> of <a href='http://www.mapsofindia.com/india.html' class='header-text2'>India</a></div><div class='header-text3'>India's No. 1 Maps Site Since 1998</div></div><div id='red-partition'><img src='http://www.business.mapsofindia.com/images-new/red-partition.gif' width='3' height='52' border='0' alt='' /></div><div id='header-text'><a href='http://business.mapsofindia.com/' class='header-text'><h1>India Business Directory</h1></a></div><div id='search-box' ><form action='http://business.mapsofindia.com/search.html' id='cse-search-box'><span class='txt-search'>Search</span> &nbsp; <input type='hidden' name='cx' value='partner-pub-0641096029648877:beh6me-wtsf' /><input type='hidden' name='cof' value='FORID:10' /><input type='hidden' name='ie' value='ISO-8859-1' /><input type='text' name='q' size='25' /><input type='submit' name='sa' value=' ' alt='' class='img_middle_srch' /></form><script type='text/javascript' src='http://www.google.co.in/cse/brand?form=cse-search-box&amp;lang=en'></script></div><!-- Header end -->");
}
function footer()
{
	document.write("<div id='footer_links'>			<ul>				<li><a href='http://www.mapsofindia.com/aboutus.html' itle='About Us'>About Us</a></li>				<li><a href='http://business.mapsofindia.com/feedback.html' itle='Feedback'>Feedback</a></li>				<li><a href='http://business.mapsofindia.com/sitemap.html' title='Site Map'>Site Map</a></li><li><a href='http://business.mapsofindia.com/sitemap.xml' title='XML Site Map'>XML Site Map</a></li>				<li><a href='http://www.mapsofindia.com/link/' title='Link To Us'>Link To Us</a></li>				<li lass='last'><a href='http://business.mapsofindia.com/rss.xml' title='RSS Feeds'>RSS Feeds</a></li>			</ul>			</div>			<div class='CL'></div>			<div id='footer_intrnl'>				<div class='FL'><img src='http://business.mapsofindia.com/images/comparelogo.gif' width='60' height='87' border='0' alt='' /></div>				<div class='FL'><div class='txt_footer'>Copyright 1999-2010 Mapsofindia.com<br />				Mapping Digiworld Pvt Ltd (An ISO 9001:2000 Certified Company)<br />								ALL RIGHTS RESERVED</div>			</div>")
}
	function rightpanel()
{
	document.write("<div><a href='http://openx.mapsofindia.com/www/delivery/ck.php?n=afe3cf40&amp;cb=INSERT_RANDOM_NUMBER_HERE' target='_blank'><img src='http://openx.mapsofindia.com/www/delivery/avw.php?zoneid=63&amp;cb=INSERT_RANDOM_NUMBER_HERE&amp;n=afe3cf40' border='0' alt='' /></a></div>")
}