# Generated by Django 5.0.6 on 2024-07-12 10:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200625_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('care_tips', 'Car Care Tips'), ('industry_news', 'India Automobile Industry')], max_length=20)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='auto_news/')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
