# Generated by Django 5.1.4 on 2026-03-14 17:36

import django.core.validators
import images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for the image', max_length=255)),
                ('image', models.ImageField(help_text='Upload image file', upload_to=images.models.get_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])])),
                ('page_reference', models.CharField(choices=[('auto_news', 'Auto News Page'), ('trucks', 'Trucks Page'), ('buses', 'Buses Page'), ('shows', 'Auto Shows Page'), ('used_cars', 'Used Cars Page'), ('petrol_stations', 'Petrol Stations Page'), ('about', 'About Page'), ('general', 'General Purpose')], default='general', help_text='Page where this image will be used', max_length=50)),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this image is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dynamic Image',
                'verbose_name_plural': 'Dynamic Images',
                'db_table': 'dynamic_images',
                'ordering': ['-created_at'],
            },
        ),
    ]
