# Generated by Django 5.1.4 on 2026-04-03 11:38

import django.core.validators
import images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike')], help_text='Type of vehicle (car or bike)', max_length=10)),
                ('brand', models.CharField(help_text='Vehicle brand (e.g., Toyota, Honda, Royal Enfield)', max_length=100)),
                ('category', models.CharField(blank=True, help_text='Vehicle category (e.g., SUV, Sedan, Sports Bike, Cruiser)', max_length=100)),
                ('model_name', models.CharField(blank=True, help_text='Specific model name this image is for', max_length=100)),
                ('image', models.ImageField(help_text='Upload vehicle image', upload_to=images.models.get_vehicle_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])])),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary image for the vehicle')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this image is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle Image',
                'verbose_name_plural': 'Vehicle Images',
                'db_table': 'vehicle_images',
                'ordering': ['-is_primary', '-created_at'],
                'indexes': [models.Index(fields=['vehicle_type', 'brand'], name='vehicle_ima_vehicle_8e5e11_idx'), models.Index(fields=['vehicle_type', 'category'], name='vehicle_ima_vehicle_a97025_idx'), models.Index(fields=['brand', 'model_name'], name='vehicle_ima_brand_06a6d9_idx')],
            },
        ),
    ]
