# Generated by Django 5.0.6 on 2024-07-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobile_company', '0002_historyarticle_sidebarlink_carmodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purpose', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lubricant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('usage', models.TextField()),
            ],
        ),
    ]
