# Generated by Django 5.0.6 on 2024-07-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobile_company', '0003_additive_lubricant'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyarticle',
            name='carModels',
            field=models.ManyToManyField(blank=True, related_name='articles', to='automobile_company.carmodels'),
        ),
    ]
