# Generated by Django 5.0.6 on 2024-07-29 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobile_company', '0004_historyarticle_carmodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodels',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_model', to='automobile_company.historyarticle'),
        ),
        migrations.AlterField(
            model_name='historyarticle',
            name='carModels',
            field=models.ManyToManyField(blank=True, related_name='articles', to='automobile_company.carmodel'),
        ),
    ]
