# Generated by Django 5.0.6 on 2024-07-29 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automobile_company', '0005_alter_carmodels_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodels',
            name='article',
        ),
    ]
