# Generated by Django 5.0.6 on 2024-07-29 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobile_company', '0007_alter_historyarticle_carmodels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyarticle',
            name='carModels',
        ),
        migrations.AddField(
            model_name='carmodels',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_models', to='automobile_company.historyarticle'),
        ),
    ]
