# Generated by Django 5.0.6 on 2024-08-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobile_company', '0008_remove_historyarticle_carmodels_carmodels_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
