# Generated by Django 5.0.6 on 2024-08-09 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automobile_company', '0009_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
