# Generated by Django 3.0.7 on 2026-01-23

from django.db import migrations
import django.utils.timezone
from decimal import Decimal

def create_sample_data(apps, schema_editor):
    # We get the models from the versioned app registry
    Company = apps.get_model('automobile_company', 'Company')
    ProfitData = apps.get_model('automobile_company', 'ProfitData')
    News = apps.get_model('automobile_company', 'News')
    
    # Create sample companies
    companies_data = [
        {
            'name': 'Tata Motors',
            'logo_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Tata_Motors_Logo.svg/2560px-Tata_Motors_Logo.svg.png',
            'description': 'Tata Motors Limited is an Indian multinational automotive manufacturing company, headquartered in Mumbai, Maharashtra, India.'
        },
        {
            'name': 'Mahindra & Mahindra',
            'logo_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Mahindra_Rise.svg/2560px-Mahindra_Rise.svg.png',
            'description': 'Mahindra & Mahindra Limited is an Indian multinational car manufacturing corporation headquartered in Mumbai, Maharashtra.'
        },
        {
            'name': 'Maruti Suzuki',
            'logo_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Maruti_Suzuki_logo.svg/2560px-Maruti_Suzuki_logo.svg.png',
            'description': 'Maruti Suzuki India Limited, formerly known as Maruti Udyog Limited, is an automobile manufacturer in India.'
        },
        {
            'name': 'Hyundai India',
            'logo_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Hyundai_Motor_Company_logo.svg/2560px-Hyundai_Motor_Company_logo.svg.png',
            'description': 'Hyundai Motor India Limited is a wholly owned subsidiary of Hyundai Motor Company, South Korea.'
        },
        {
            'name': 'Toyota Kirloskar',
            'logo_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Toyota_logo.svg/2560px-Toyota_logo.svg.png',
            'description': 'Toyota Kirloskar Motor Private Limited is an Indian joint venture between Toyota Motor Corporation and Kirloskar Group.'
        },
        {
            'name': 'Honda Cars India',
            'logo_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Honda_logo.svg/2560px-Honda_logo.svg.png',
            'description': 'Honda Cars India Ltd. (HCIL) is a subsidiary of Honda Motor Co. Ltd., Japan.'
        }
    ]
    
    created_companies = []
    for company_data in companies_data:
        company = Company.objects.create(**company_data)
        created_companies.append(company)
    
    # Create profit data for the last 3 years
    years = [2023, 2022, 2021]
    profit_values = [
        [Decimal('15000.50'), Decimal('12000.30'), Decimal('10000.20')],  # Tata Motors
        [Decimal('8500.75'), Decimal('7200.40'), Decimal('6500.80')],      # Mahindra
        [Decimal('12000.00'), Decimal('11000.50'), Decimal('9500.30')],    # Maruti Suzuki
        [Decimal('9000.25'), Decimal('8500.75'), Decimal('7800.90')],      # Hyundai
        [Decimal('11000.60'), Decimal('9800.40'), Decimal('8900.70')],     # Toyota
        [Decimal('7500.80'), Decimal('6800.20'), Decimal('6200.50')],      # Honda
    ]
    
    for i, company in enumerate(created_companies):
        for j, year in enumerate(years):
            ProfitData.objects.create(
                company=company,
                year=year,
                profit=profit_values[i][j]
            )
    
    # Create sample news
    news_data = [
        {
            'title': 'Tata Motors Launches New Electric Vehicle',
            'summary': 'Tata Motors has announced the launch of its latest electric vehicle, marking a significant step in India\'s EV revolution.',
            'image_url': 'https://via.placeholder.com/400x200/007bff/ffffff?text=Tata+EV+News',
            'url': 'https://example.com/tata-ev-news',
            'pub_date': django.utils.timezone.now()
        },
        {
            'title': 'Maruti Suzuki Reports Record Sales',
            'summary': 'Maruti Suzuki has reported its highest quarterly sales, driven by strong demand for compact cars.',
            'image_url': 'https://via.placeholder.com/400x200/28a745/ffffff?text=Maruti+Sales',
            'url': 'https://example.com/maruti-sales',
            'pub_date': django.utils.timezone.now()
        },
        {
            'title': 'Hyundai Expands Manufacturing in India',
            'summary': 'Hyundai Motor India announces expansion plans for its manufacturing facility in Tamil Nadu.',
            'image_url': 'https://via.placeholder.com/400x200/dc3545/ffffff?text=Hyundai+Expand',
            'url': 'https://example.com/hyundai-expansion',
            'pub_date': django.utils.timezone.now()
        },
        {
            'title': 'Electric Vehicle Market Growth in India',
            'summary': 'The Indian electric vehicle market shows promising growth with increased consumer adoption.',
            'image_url': 'https://via.placeholder.com/400x200/6f42c1/ffffff?text=EV+Market',
            'url': 'https://example.com/ev-market-growth',
            'pub_date': django.utils.timezone.now()
        },
        {
            'title': 'Toyota Introduces Hybrid Technology',
            'summary': 'Toyota Kirloskar Motor introduces advanced hybrid technology in its latest models for the Indian market.',
            'image_url': 'https://via.placeholder.com/400x200/fd7e14/ffffff?text=Toyota+Hybrid',
            'url': 'https://example.com/toyota-hybrid',
            'pub_date': django.utils.timezone.now()
        },
        {
            'title': 'Honda Focuses on Safety Features',
            'summary': 'Honda Cars India emphasizes advanced safety features across its vehicle lineup.',
            'image_url': 'https://via.placeholder.com/400x200/20c997/ffffff?text=Honda+Safety',
            'url': 'https://example.com/honda-safety',
            'pub_date': django.utils.timezone.now()
        }
    ]
    
    for news_item in news_data:
        News.objects.create(**news_item)

def delete_sample_data(apps, schema_editor):
    Company = apps.get_model('automobile_company', 'Company')
    ProfitData = apps.get_model('automobile_company', 'ProfitData')
    News = apps.get_model('automobile_company', 'News')
    
    # Delete all sample data
    News.objects.all().delete()
    ProfitData.objects.all().delete()
    Company.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('automobile_company', '0012_news_pub_date'),
    ]

    operations = [
        migrations.RunPython(create_sample_data, delete_sample_data),
    ]
