# Generated by Django 5.0.6 on 2024-07-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('wheelbase', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('trunk', models.CharField(max_length=100)),
                ('tank', models.CharField(max_length=100)),
                ('engine', models.CharField(max_length=100)),
                ('gears', models.CharField(max_length=100)),
                ('fueleconomy', models.CharField(max_length=100)),
                ('speed', models.CharField(max_length=100)),
                ('image', models.ImageField(max_length=1000, upload_to='')),
                ('manufac_place', models.CharField(max_length=100)),
                ('Vehicle_overview', models.TextField(null=True)),
                ('features', models.TextField(null=True)),
            ],
        ),
    ]
