# Generated by Django 5.0.6 on 2024-07-23 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='company',
            new_name='category',
        ),
    ]
