# Generated by Django 5.0.6 on 2024-08-07 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_rename_company_bike_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='category',
            new_name='categoryBike',
        ),
    ]
