# Generated by Django 5.0.6 on 2025-02-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0003_rename_category_bike_categorybike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='engine',
            new_name='Bikemodel',
        ),
        migrations.RenameField(
            model_name='bike',
            old_name='fueleconomy',
            new_name='Bikename',
        ),
        migrations.RenameField(
            model_name='bike',
            old_name='manufac_place',
            new_name='body_type',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='Vehicle_overview',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='model',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='name',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='tank',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='trunk',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='type',
        ),
        migrations.AddField(
            model_name='bike',
            name='engine_capacity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='engine_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='fuel_tank_capacity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('CNG', 'CNG'), ('Hybrid', 'Hybrid')], max_length=50),
        ),
        migrations.AddField(
            model_name='bike',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bike',
            name='manufacturing_place',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bike',
            name='manufacturing_year',
            field=models.PositiveIntegerField(default=2022),
        ),
        migrations.AddField(
            model_name='bike',
            name='max_speed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='mileage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='motor_power',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='number_of_cylinders',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='trunk_capacity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='user_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bike',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='gears',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='image',
            field=models.ImageField(upload_to='bike_images/'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='wheelbase',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='vehicle_overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
