# Generated by Django 5.0.6 on 2026-01-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0004_rename_engine_bike_bikemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
