# Generated by Django 6.0.2 on 2026-02-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0005_bike_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='price',
            field=models.IntegerField(help_text='Price in rupees (integer)'),
        ),
    ]
